import '~styles/globals.css'

import { Header } from '~components/header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body>
        <Header />

        <div className={'flex justify-center'}>
          <div className={'container px-1'}>{children}</div>
        </div>
      </body>
    </html>
  )
}
